### ISSUE TITLE
对接onebot实现时出现问题

### ISSUE THREAD

**Issue by Apricityx** [koishijs/koishi-plugin-adapter-onebot#12]
对接的项目地址：https://github.com/YDHusky/LiteLoaderQQNT-OneBotApi
当插件启动时，报错如下：
![image](https://github.com/koishijs/koishi-plugin-adapter-onebot/assets/78242039/3faef345-4315-4a8f-b555-79436c094939)
当接收到消息时，报错如下：
![image](https://github.com/koishijs/koishi-plugin-adapter-onebot/assets/78242039/da1b3029-9a43-4a87-bf20-ba0cf6858c2f)
配置信息如下：
![image](https://github.com/koishijs/koishi-plugin-adapter-onebot/assets/78242039/a0e74be8-f1be-4909-bf71-4b7de847e7ac)
127.0.0.1:3001正常访问
上报地址为http://127.0.0.1:5140/onebot
5140为koishi端口
机器人状态显示为绿灯
![image](https://github.com/koishijs/koishi-plugin-adapter-onebot/assets/78242039/c1f805b4-3889-40b6-a3a2-31d88b2c9496)

**Comment by shigma** [comment]
[LiteLoaderQQNT-OneBotApi](https://github.com/YDHusky/LiteLoaderQQNT-OneBotApi) 没有支持足够的 OneBot API。

- get_msg
- sender

**Comment by Apricityx** [comment]
测试发现文字消息能正常发送，图片消息发送不了，koishi端无报错
