### ISSUE TITLE
重复事件guild-member-added

### ISSUE THREAD

**Issue by hutuyee** [koishijs/koishi-plugin-adapter-onebot#22]
guild-member-add多次触发，源代码如下
![{679E64DD-F330-499c-A746-641902BB2290}](https://github.com/koishijs/koishi-plugin-adapter-onebot/assets/110071800/1c779b2f-0d05-4753-9396-66172463a555)

**Comment by shigma** [comment]
能打印一下 session.id 和 session.userId 吗，看看是不是相同的

**Comment by hutuyee** [comment]
不好意思，这是LLonebot的问题，已被他们解决
发件人: ***@***.***>
发送时间: 2024年3月26日 21:04
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [koishijs/koishi-plugin-adapter-onebot] 重复事件guild-member-added (Issue #22)


能打印一下 session.id 和 session.userId 吗，看看是不是相同的

―
