### ISSUE TITLE
message_sent 无法触发koishi middleware

### ISSUE THREAD

**Issue by garveen** [koishijs/koishi-plugin-adapter-onebot#27]
post_type为message_sent的时候，尽管本插件有相关处理，但是在koishi自定义plugin的middleware里面，无法触发事件。

**Comment by garveen** [comment]
https://github.com/koishijs/koishi/issues/1403
本质是koishi-core的问题，但是和本插件相关

**Comment by shigma** [comment]
实际上 message_sent 无论如何都不会触发 middleware，只有 message 会触发。

你的问题实际上分为两个：

1. onebot 接收到 message_sent 的时候是否应该触发 message（是的，已经实现）
2. 由自身触发的 message 事件是否应该由 middleware 处理（目前不处理，已经在新 issue 中讨论）

close due to duplicate of https://github.com/koishijs/koishi/issues/1403
