### ISSUE TITLE
一直error报错以及状态灰色但是能使用

### ISSUE THREAD

**Issue by lumia1998** [koishijs/koishi-plugin-adapter-onebot#31]
环境:docker
对接:napcat (docker)
具体报错:
![image](https://github.com/koishijs/koishi-plugin-adapter-onebot/assets/63107956/e2a15d90-33bc-443e-a1f9-7224adc327b5)
出现这种qi情况后就koishi无法接受任何qq发送的消息
![image](https://github.com/koishijs/koishi-plugin-adapter-onebot/assets/63107956/54e23023-6846-4f27-83b1-7e2388f8d93d)
这个开关有时候开,有时候关闭,koishi上的qq状态会变成绿色之后qq恢复正常,但是过段时间qq又会变成灰色,但是能用.

**Comment by lumia1998** [comment]
6.5.4正常

**Comment by shigma** [comment]
如果最新版不报错的话此 issue 可以关闭。

**Comment by lumia1998** [comment]
重建实例正常了
但是目前还是docker的koishi和docker的napcat(无头qq类llob),状态是灰色的,但是不影响使用

**Comment by itzdrli** [comment]
同 napcat，不是docker，无法复现

**Comment by lumia1998** [comment]
> 同 napcat，不是docker，无法复现
> 
> 补：napcat-docker也正常

奇怪了我用一段时间就会变成灰色,但是上上上上个版本就没问题
重新起的koishi也这样

**Comment by shigma** [comment]
由于没有其他人复现此 issue，推测是你的 docker 配置的问题。

**Comment by Lipraty** [comment]
你是 author，可以自己关闭的
