### ISSUE TITLE
改变机器人的qq号后出现问题

### ISSUE THREAD

**Issue by jry2010** [koishijs/koishi-plugin-adapter-onebot#41]
把一个qq账号作为机器人拉到两个群里后可以正常工作，把机器人换成另外一个qq账号后，新的机器人不再在这两个群里工作

**Comment by shigma** [comment]
请查看文档：https://koishi.chat/zh-CN/manual/usage/customize.html#%E5%8F%97%E7%90%86%E4%BA%BA%E6%9C%BA%E5%88%B6

简单来说，你可以采用以下做法中的**任意一种**：

- 使用 admin 这样的插件设置 assignee
- 手动修改数据库中的 assignee
- 清空数据库文件
