### ISSUE TITLE
使用session.onebot.downloadFile时提示TypeError: Cannot read properties of undefined (reading 'downloadFile')

### ISSUE THREAD

**Issue by Cola-Ace** [koishijs/koishi-plugin-adapter-onebot#42]
如题，qq方面是支持这个api的，但是koishi内调用时提示如上，adapter-onebot为最新版

**Comment by Cola-Ace** [comment]
另外，在调用session.bot.getForwardMsg的时候总是timeout，而通过api调试工具直接像qq发送请求则正常

**Comment by shigma** [comment]
onebot 没有这个 API。你是不是把 onebot 跟其他协议搞混了？

**Comment by Cola-Ace** [comment]
go-cqhttp支持这个，而且我看代码中也有相关的函数
![PixPin_2024-07-31_02-30-39](https://github.com/user-attachments/assets/88ce410f-24f0-43e8-af33-1af778680030)

**Comment by Cola-Ace** [comment]
> 另外，在调用session.bot.getForwardMsg的时候总是timeout，而通过api调试工具直接向qq发送请求则正常

顺便能请您看看这个问题发生的原因吗

**Comment by shigma** [comment]
> 另外，在调用session.bot.getForwardMsg的时候总是timeout，而通过api调试工具直接向qq发送请求则正常

应该是 session.onebot.getForwardMsg 对吧？

**Comment by shigma** [comment]
> TypeError: Cannot read properties of undefined (reading 'downloadFile')

这个说明 `session.onebot` 可能就不存在。你是在什么情况下调用的？能看看代码吗？

**Comment by Cola-Ace** [comment]
> > TypeError: Cannot read properties of undefined (reading 'downloadFile')
> 
> 这个说明 `session.onebot` 可能就不存在。你是在什么情况下调用的？能看看代码吗？

我用qqbot.internal.downloadFile就好了，应该是我在discord发送消息时session.onebot不存在的问题

**Comment by Cola-Ace** [comment]
> > 另外，在调用session.bot.getForwardMsg的时候总是timeout，而通过api调试工具直接向qq发送请求则正常
> 
> 应该是 session.onebot.getForwardMsg 对吧？
> 
> 可能需要看看请求参数。

`{ messageId: '-2147483038', id: '-2147483038', elements: [{ type: 'forward', attrs: { id: '7397666445403751866' }, children: []}], content: '<forward id="7397666445403751866"/>' }`
我传入的参数是`elements[0].attrs.id`，且具体代码中我会确保该element的type为forward，所以传入的参数应该是没问题的
![PixPin_2024-07-31_13-32-34](https://github.com/user-attachments/assets/9ac3f6b4-6dd1-4c84-be46-419098f370e4)
 另外，我发现我传入的forward_id和报错消息中的message_id不一致（`[I]`的是初始的forward_id）

**Comment by shigma** [comment]
那这个 issue 本身的问题应该算解决了。

后面提的这个问题我怎么感觉是返回了超出整型限制的大数？能看看你的代码吗？

**Comment by shigma** [comment]
可能相关：https://github.com/koishijs/koishi-plugin-adapter-onebot/issues/9

**Comment by Cola-Ace** [comment]
相关测试代码如下：
![PixPin_2024-08-08_16-43-06](https://github.com/user-attachments/assets/f50683d8-47e4-45b4-b23e-59cd58ee305b)
在当前情景下，我确保session.onebot是可用的，且我传入该函数的参数的类型确定为string而不是整型

**Comment by shigma** [comment]
已修复。
