### ISSUE TITLE
Bug: 无法通过koishi api发送文件

### ISSUE THREAD

**Issue by soundofautumn** [koishijs/koishi-plugin-adapter-onebot#45]
复现代码如下：
```ts
const h_image = h.image(
  'file:///D:/Project/koishi-app/temp/ffxiv-raid-helper/1.png'
);
logger.debug('to send:', h_image);
await session.send(h_image);
const h_file = h.file(
  'file:///D:/Project/koishi-app/temp/ffxiv-raid-helper/1.png'
);
logger.debug('to send:', h_file);
await session.send(h_file);
```

日志输出：
```
[D] ffxiv-raid-helper to send: Element { type: 'img', attrs: { src: 'file:///D:/Project/koishi-app/temp/ffxiv-raid-helper/1.png' }, children: [] }
[D] ffxiv-raid-helper to send: Element { type: 'file', attrs: { src: 'file:///D:/Project/koishi-app/temp/ffxiv-raid-helper/1.png' }, children: [] }
```

上面以h.image创建的图像能正常发送，而下面file类型的无法发送
onebot日志中只有第一次图片的发送记录，没有第二次的

通过session.onebot.sendPrivateMsg和session.onebot.sendGroupMsg并使用CQ码发送文件成功，所以怀疑是适配器不支持导致的

**Comment by shigma** [comment]
适配器确实没有实现文件发送。

onebot 11 协议规范里好像也没有说 file CQ，你使用的是哪一个 onebot 实现？

**Comment by soundofautumn** [comment]
我本地测试用的是LLOneBot

**Comment by shigma** [comment]
发送方式直接是 [CQ:file,url=] 吗？

**Comment by soundofautumn** [comment]
具体不是很清楚，我在 #46 加了支持后能发送了

**Comment by soundofautumn** [comment]
2024-08-13 10:53:26 [D] onebot [request] send_private_msg { user_id: *, message: [ { type: 'file', data: { name: '115团.csv', file: 'base64://somebase64', cache: 0 } } ], auto_escape: undefined }
2024-08-13 10:53:27 [D] onebot [request] send_private_msg { user_id: 1298528323, message: [ { type: 'file', data: { file: 'file:///D:/Project/koishi-app/temp/ffxiv-raid-helper/115%E5%9B%A2-20240813105326.csv', cache: 0 } } ], auto_escape: undefined }

**Comment by soundofautumn** [comment]
使用的代码如下：
const file = h.file(buffer, 'text/csv');
file.attrs.name = `${team_name}.csv`;
await session.send(file);
await session.send(h.file(pathToFileURL(file_path).href));

**Comment by shigma** [comment]
可以，那我直接合并啦，感谢贡献！

**Comment by shigma** [comment]
6.5.13
